import type { Metadata } from "next";
import { Gowun_Dodum } from "next/font/google";
import "./globals.css";

import Header from "./components/Header";
import TopButton from "./components/TopButton";

const gowunDodum = Gowun_Dodum({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Next Quiz App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={gowunDodum.className + " bg-slate-200 min-h-[100vh] max-w-full flex flex-col justify-between"}>
        <Header />

        {children}

        <TopButton />

        <footer className="w-full mx-auto bg-emerald-600 p-6 text-center text-slate-200">
          Quiz &copy; <a href="https://quizapi.io/" target="_blank">QuizAPI</a>
        </footer>
      </body>
    </html>
  );
}
